%% Automate Importing Data by Generating Code Using the Database Explorer App
% This code reproduces the data obtained using the Database Explorer app by
% connecting to a database, executing a SQL query, and importing data into the
% MATLAB(R) workspace. To use this code, add the password for connecting to the
% database in the database command.

% Auto-generated by MATLAB (R2022b) and Database Toolbox Version 10.4 on 18-May-2023 13:56:23

%% Make connection to database
conn = database('china_stock','root','Hangzhou123');

%Set query to execute on the database
query1 = ['SELECT time, time1, lastPrice, stock ' ...
    'FROM market_research.quote ' ...
    'WHERE time <= "2023-05-31 09:00:00" and time >= "2023-05-30 09:00:00" ' ...
    'ORDER BY time ASC'];
query2 = ['SELECT time, stock, close ' ...
    'FROM market_research.etf1m ' ...
    'WHERE time <= "2023-05-31 09:00:00" and time >= "2023-05-30 09:00:00" ' ...    
    'ORDER BY time ASC'];
%% Set Database Import Options
opts1 = databaseImportOptions(conn,query1);
opts2 = databaseImportOptions(conn,query2);
%Update Variable Types
opts1 = setoptions(opts1,{'time'},'Type',{'datetime'});
opts2 = setoptions(opts2,{'time'},'Type',{'datetime'});
%% Execute query and fetch results
data_quote = fetch(conn,query1,opts1);
data_etf1m = fetch(conn,query2,opts2);
data_quote=data_quote(end-3600:end,:);
data_etf1m=data_etf1m(end-3600:end,:);

dt = minutes(10);
idx=strcmp(data_quote.stock, '510330.SH');
etf1=data_quote(idx,["time","lastPrice"]);
TT1 = array2timetable(etf1.lastPrice,'RowTimes',etf1.time,'VariableNames',"510350.SH");
TT2 = retime(TT1,'regular','firstvalue','TimeStep',dt);
TT22 = retime(TT1,'regular','nearest','TimeStep',dt);
hhmm=TT2.Time.Hour*100+TT2.Time.Minute;
idx=(hhmm>=930 & hhmm<=1130) | (hhmm>=1300 & hhmm<=1500);
TT2=TT2(idx,:);
TT22=TT22(idx,:);

idx=strcmp(data_quote.stock, '510300.SH');
etf2=data_quote(idx,["time","lastPrice"]);
TT3 = array2timetable(etf2.lastPrice,'RowTimes',etf2.time,'VariableNames',"510330.SH");
TT4 = retime(TT3,'regular','firstvalue','TimeStep',dt);
TT44 = retime(TT3,'regular','firstvalue','TimeStep',dt);
hhmm=TT4.Time.Hour*100+TT4.Time.Minute;
idx=(hhmm>=930 & hhmm<=1130) | (hhmm>=1300 & hhmm<=1500);
TT4=TT4(idx,:);
TT44=TT44(idx,:);
TT=[TT2,TT4];

lastPrice_tick= unstack(data_quote, 'lastPrice', 'stock', 'VariableNamingRule','preserve');
lastPrice_10m=modifyFrequency(lastPrice_tick, dt);

[TT2.("510350.SH") lastPrice_10m.("510350.SH")]

%% Close connection to database
close(conn)

%% Clear variables
clear conn query1 query1

