function [obj, grad] = objective2(inputVariables, extraParams)
%objective2 Compute objective function value
%
%   This function computes the objective value.
%   Update the generated code to add the objective gradient computation.
%
%   OBJ = objective2(INPUTVARIABLES, EXTRAPARAMS) computes the objective
%   value OBJ at the point INPUTVARIABLES, using the extra parameters in
%   EXTRAPARAMS.
%
%   [OBJ, GRAD] = objective2(INPUTVARIABLES, EXTRAPARAMS) additionally
%   computes the objective gradient value GRAD at the current point.
%
%   Auto-generated by prob2struct on 07-May-2023 17:24:24

%% Variable indices.
widx = 1;
xidx = 2:4;

%% Map solver-based variables to problem-based.
w = inputVariables(widx);
x = inputVariables(xidx);
x = x(:)';

if nargout > 1
    %% Insert gradient calculation here.
    % To call the gradient code, notify the solver by setting the
    % SpecifyObjectiveGradient option to true.
    grad = [];
end

%% Compute objective function.
generatedFunction_sharpe = extraParams{7};
obj = generatedFunction_sharpe(extraParams{1}, (x ./ 50), (w ./ 50), extraParams{2}, extraParams{3}, 24, extraParams{4}, extraParams{5}, extraParams{6});
end